services:
  fagus:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: fagus
    restart: unless-stopped
    ports:
      - "3080:80"
    volumes:
      - wp_content:/var/www/wordpress/wp-content
    environment:
      # WordPress Site URL (anpassen an echte Domain)
      - WP_URL=http://91.99.188.249:3080
      # Next.js WordPress API (intern im Container: Next.js -> Nginx -> PHP-FPM)
      - WP_API_URL=http://localhost/wp-json/wp/v2
      # E-Mail / SMTP (fuer Kontaktformular)
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_SECURE=false
      - SMTP_USER=
      - SMTP_PASS=
      - CONTACT_EMAIL=hallo@broetzens.de
      # WordPress Debug (optional)
      # - WP_DEBUG=true
    networks:
      - proxy

volumes:
  wp_content:

networks:
  proxy:
    external: true
