services:
  fagus:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: fagus
    restart: unless-stopped
    volumes:
      - wp_content:/var/www/wordpress/wp-content
    environment:
      # WordPress Site URL (anpassen an echte Domain)
      - WP_URL=https://broetzens.de
      # Next.js WordPress API (intern im Container)
      - WP_API_URL=http://localhost/wp-json/wp/v2
      # E-Mail / SMTP (fuer Kontaktformular)
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_SECURE=false
      - SMTP_USER=
      - SMTP_PASS=
      - CONTACT_EMAIL=kontakt@broetzens.de
      # WordPress Debug (optional)
      # - WP_DEBUG=true
    networks:
      - proxy

volumes:
  wp_content:

networks:
  proxy:
    external: true
